# Generated by Django 4.2 on 2023-04-30 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='news_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsitem'),
        ),
    ]
