# Generated by Django 4.2 on 2023-04-30 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_favorite_news_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(blank=True, max_length=255, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('news_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.newsitem')),
            ],
        ),
        migrations.DeleteModel(
            name='CachedNews',
        ),
    ]
