# Generated by Django 4.2 on 2023-05-01 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_newscache_delete_cachednews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newscache',
            old_name='timestamp',
            new_name='last_fetched',
        ),
    ]
