# Generated by Django 4.2 on 2023-05-01 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_timestamp_newscache_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscache',
            name='last_fetched',
            field=models.DateTimeField(),
        ),
    ]
