# Generated by Django 4.2 on 2023-05-01 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_newscache_last_fetched'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscache',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
