# Generated by Django 4.2 on 2023-05-01 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_newscache_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newscache',
            name='last_fetched',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
