# Generated by Django 4.2 on 2023-05-01 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_query_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachednewsitem',
            name='query',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Query',
        ),
    ]
