# Generated by Django 4.2 on 2023-05-01 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_favourite_delete_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='favourite',
        ),
    ]
