# Generated by Django 4.2 on 2023-05-01 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_favourite_favourite'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='is_favourite',
            field=models.BooleanField(default=True),
        ),
    ]
